import json
import random
from collections import Counter

random.seed(42)

titols_per_materia = {
    "Arquitectura": [
        "Introducció a l'arquitectura moderna", "Teoria de l'arquitectura contemporània",
        "Història de l'arquitectura occidental", "Arquitectura i urbanisme al segle XXI",
        "Els grans arquitectes del món", "Arquitectura sostenible i medi ambient",
        "Principis d'arquitectura", "Arquitectura i societat",
        "Diccionari d'arquitectura", "L'arquitectura com a art",
        "Fonaments de l'arquitectura", "Arquitectura i cultura",
        "Introduction to Architecture", "Modern Architecture: A Critical History",
        "The Language of Architecture", "Architecture and Power",
        "Arquitectura y ciudad", "Historia de la arquitectura universal",
        "Teoría de la arquitectura", "Arquitectura contemporánea",
        "De architectura", "Vitruvii de architectura libri decem",
        "Space, Time and Architecture", "Towards a New Architecture",
        "Arquitectura i espai urbà", "Forma i funció en arquitectura",
        "Nous corrents en arquitectura", "Arquitectura bioclimàtica",
        "Arquitectura i paisatge", "El lenguaje de la arquitectura moderna",
        "Arquitectura popular", "Arquitectura vernacla",
        "Arquitectura religiosa", "Arquitectura civil i militar",
        "Arquitectura domèstica", "Arquitectura i tecnologia",
        "Parametric Architecture", "Digital Fabrication in Architecture",
        "Green Architecture", "Sustainable Design Strategies",
        "Arquitectura efímera", "Arquitectura i memòria",
        "Arquitectura i poder", "Els materials en arquitectura",
        "La llum en arquitectura", "Arquitectura i música",
        "Proporcions i geometria en arquitectura", "Arquitectura i filosofia",
        "Crítica arquitectònica", "Teoria i pràctica de l'arquitectura",
    ],
    "Arquitectura--Catalunya": [
        "L'arquitectura catalana medieval", "El modernisme arquitectònic a Catalunya",
        "Arquitectura contemporània a Catalunya", "Gaudí i el modernisme català",
        "L'arquitectura gòtica catalana", "Cases i palaus de Catalunya",
        "L'arquitectura romànica a Catalunya", "Arquitectes catalans del segle XX",
        "L'arquitectura noucentista a Catalunya", "Barcelona i la seva arquitectura",
        "Els monestirs catalans", "Arquitectura industrial a Catalunya",
        "L'arquitectura popular catalana", "Masies i arquitectura rural catalana",
        "Torres i castells de Catalunya", "L'arquitectura religiosa a Catalunya",
        "Esglésies romàniques catalanes", "Catedrals catalanes",
        "Palaus gòtics de Barcelona", "L'Eixample de Barcelona",
        "Arquitectura del segle XIX a Catalunya", "El Palau de la Música Catalana",
        "La Sagrada Família: arquitectura i símbol", "Lluís Domènech i Montaner",
        "Josep Puig i Cadafalch, arquitecte", "L'obra arquitectònica de Coderch",
        "Arquitectura racionalista a Catalunya", "El GATCPAC i l'arquitectura moderna",
        "L'arquitectura de la postguerra a Catalunya", "Nova arquitectura catalana",
        "L'arquitectura olímpica de Barcelona", "Barcelona 1992: transformació urbana",
        "El barri Gòtic de Barcelona", "Arquitectura del Poblenou",
        "Girona arquitectònica", "L'arquitectura de Lleida",
        "Tarragona: arquitectura romana i medieval", "Arquitectura modernista fora de Barcelona",
        "Reus i el modernisme", "Arquitectura rural del Pirineu català",
        "Cases pairals catalanes", "Arquitectura i territori a Catalunya",
        "L'arquitectura dels anys 60 a Catalunya", "Arquitectes catalans contemporanis",
        "L'arquitectura de les Terres de l'Ebre", "El Born i la seva arquitectura",
        "Arquitectura del Poblenou industrial", "L'arquitectura de la Barceloneta",
        "Habitatge social a Catalunya", "L'arquitectura efímera a Catalunya",
    ],
    "Arquitectura--S.XX": [
        "L'arquitectura del segle XX", "Moviments arquitectònics del segle XX",
        "El Moviment Modern en arquitectura", "Arquitectura i avantguardes al segle XX",
        "De la Bauhaus al deconstructivisme", "L'arquitectura racionalista",
        "Le Corbusier i l'arquitectura moderna", "Mies van der Rohe: obra i pensament",
        "Frank Lloyd Wright i l'arquitectura orgànica", "Walter Gropius i la Bauhaus",
        "L'arquitectura del brutalisme", "L'arquitectura del metabolisme japonès",
        "Postmodernisme en arquitectura", "Robert Venturi i el postmodernisme",
        "L'arquitectura deconstructivista", "Frank Gehry: arquitectura i forma",
        "Zaha Hadid: una arquitectura del futur", "Rem Koolhaas i l'arquitectura contemporània",
        "L'arquitectura del high-tech", "Norman Foster i l'arquitectura tecnològica",
        "Renzo Piano: obra i pensament", "L'arquitectura minimalista",
        "Architecture of the Twentieth Century", "Modern Architecture Since 1900",
        "The International Style", "Historia de la arquitectura del siglo XX",
        "Arquitectura española del siglo XX", "L'arquitectura totalitària del segle XX",
        "L'arquitectura dels anys 50", "L'arquitectura dels anys 60",
        "L'arquitectura dels anys 70", "L'arquitectura dels anys 80",
        "L'arquitectura dels anys 90", "Arquitectura i globalització",
        "Edificis emblemàtics del segle XX", "Rascacielos del siglo XX",
        "L'arquitectura dels grans esdeveniments", "Pavilions i exposicions universals",
        "Utopies arquitectòniques del segle XX", "L'arquitectura experimental",
        "Arquitectura i ciència ficció", "Arquitectura i tecnologia al segle XX",
        "El vidre i l'acer en arquitectura", "L'arquitectura sostenible al XX",
        "Arquitectura i ecologia", "L'habitatge al segle XX",
        "L'arquitectura del transport", "Aeroports i estacions del XX",
        "Grans infraestructures del segle XX", "L'arquitectura dels museus",
    ],
    "Esports": [
        "Història de l'esport", "L'esport en la societat contemporània",
        "Filosofia de l'esport", "Sociologia de l'esport",
        "Psicologia de l'esport", "L'esport com a fenomen cultural",
        "Els Jocs Olímpics: història i valors", "L'olimpisme modern",
        "Esport i salut", "Esport i educació",
        "L'esport professional", "Negoci i esport",
        "Màrqueting esportiu", "Esport i mitjans de comunicació",
        "Esport i televisió", "Dret esportiu",
        "Administració esportiva", "Gestió d'instal·lacions esportives",
        "Esport i política", "L'esport als règims totalitaris",
        "Esport i nacionalisme", "Esport i identitat",
        "Dopatge en l'esport", "Ètica esportiva",
        "Fair play i esport", "Violència en l'esport",
        "Esport femení", "La dona en l'esport",
        "Esport i gènere", "Esport adaptat",
        "Esport paralímpic", "Esport i discapacitat",
        "Esport infantil", "Esport escolar",
        "Iniciació esportiva", "Entrenament esportiu",
        "Fisiologia de l'esport", "Medicina esportiva",
        "Nutrició esportiva", "Rendiment esportiu",
        "The History of Sport", "Sport and Society",
        "Historia del deporte", "Deporte y cultura",
        "Sport and Politics", "Olympic Games History",
        "Esport i turisme", "Instal·lacions esportives",
        "Arquitectura esportiva", "Estadis i pavellons",
    ],
    "Esports--Catalunya": [
        "Història de l'esport català", "L'esport a Catalunya al segle XX",
        "L'esport català durant el franquisme", "El moviment olímpic a Catalunya",
        "Catalunya i els Jocs Olímpics", "Barcelona 1992: els Jocs Olímpics",
        "L'esport català contemporani", "Institucions esportives catalanes",
        "La Secretaria General de l'Esport de Catalunya", "L'esport escolar a Catalunya",
        "Clubs esportius catalans", "L'esport popular a Catalunya",
        "Jocs tradicionals catalans", "Esport i catalanisme",
        "L'esport com a fet nacional català", "Seleccions esportives catalanes",
        "L'atletisme català", "El bàsquet català",
        "El tennis català", "La natació catalana",
        "El ciclisme català", "El rugbi català",
        "Esport i immigració a Catalunya", "L'esport a les comarques catalanes",
        "Instal·lacions esportives a Catalunya", "Polítiques esportives a Catalunya",
        "Esportistes catalans destacats", "Medallistes olímpics catalans",
        "L'esport femení a Catalunya", "La dona esportista catalana",
        "Esport i televisió a Catalunya", "Esport i premsa a Catalunya",
        "L'esport universitari català", "Esport i salut a Catalunya",
        "Medicina esportiva a Catalunya", "Recerca en esport a Catalunya",
        "L'INEFC: història i present", "Formació esportiva a Catalunya",
        "Esport i economia a Catalunya", "L'impacte econòmic de l'esport",
        "Turisme esportiu a Catalunya", "Esdeveniments esportius a Catalunya",
        "L'handbol català", "El voleibol català",
        "L'hoquei sobre patins a Catalunya", "El motor sport català",
        "Muntanyisme i excursionisme a Catalunya", "El Centre Excursionista de Catalunya",
        "Esport i escola a Catalunya", "La Federació Catalana d'Esports",
    ],
    "Futbol--Catalunya": [
        "Història del futbol català", "El futbol a Catalunya: orígens i evolució",
        "El FC Barcelona: història d'un club", "Barça: més que un club",
        "La història del Barça", "El Futbol Club Barcelona al segle XX",
        "Johan Cruyff i el Barça", "La filosofia del joc del Barça",
        "El sistema de joc del FC Barcelona", "La Masia: escola de futbol",
        "Messi i el Barça", "Els grans jugadors del Barça",
        "El Barça i el catalanisme", "Futbol i identitat catalana",
        "L'Espanyol de Barcelona: història", "El derbi barceloní",
        "Futbol i política a Catalunya", "El futbol català durant la República",
        "El futbol català durant el franquisme", "La repressió del futbol català",
        "La lliga catalana de futbol", "El futbol amateur català",
        "El futbol base a Catalunya", "Futbol femení a Catalunya",
        "Entrenadors catalans de futbol", "Jugadors catalans a l'estranger",
        "La selecció catalana de futbol", "La Federació Catalana de Futbol",
        "El Camp Nou: història i arquitectura", "Els estadis catalans",
        "Futbol i televisió a Catalunya", "El negoci del futbol català",
        "Futbol i economia a Catalunya", "Violència en el futbol català",
        "Les penyes del Barça", "Aficionats i futbol a Catalunya",
        "El futbol a les comarques", "Futbol i immigració a Catalunya",
        "Futbol i integració social", "Tàctiques de futbol",
        "Anàlisi tàctica del futbol modern", "Entrenament de futbol",
        "Medicina i futbol", "Futbol i tecnologia",
        "El futbol català al segle XXI", "Nous clubs catalans de futbol",
        "Futbol sala a Catalunya", "El futbol català femení",
        "Girona FC: història", "El Nàstic de Tarragona",
    ],
    "Literatura catalana": [
        "Història de la literatura catalana", "La literatura catalana: una introducció",
        "Antologia de la literatura catalana", "Els grans autors catalans",
        "La literatura catalana medieval", "Ramon Llull: vida i obra",
        "Bernat Metge i l'humanisme català", "Ausiàs March: poesia i amor",
        "Joanot Martorell i el Tirant lo Blanc", "La Renaixença catalana",
        "Jacint Verdaguer: poeta nacional", "Narcís Oller i la novel·la realista",
        "Joan Maragall: vida i poesia", "El Modernisme literari català",
        "Victor Català i la narrativa modernista", "El Noucentisme literari",
        "Josep Carner: el príncep dels poetes", "Joan Salvat-Papasseit: poesia avantguardista",
        "J.V. Foix i el surrealisme", "Carles Riba i la poesia clàssica",
        "Salvador Espriu: obra i pensament", "Pere Calders i el conte fantàstic",
        "Mercè Rodoreda i la novel·la", "La plaça del Diamant: anàlisi",
        "Joan Oliver: teatre i poesia", "Llorenç Villalonga i Bearn",
        "Gabriel Ferrater: poesia i crítica", "Miquel Martí i Pol: el poeta de Roda",
        "Joan Brossa: poesia visual", "La literatura catalana de postguerra",
        "Literatura catalana i exili", "La novel·la catalana contemporània",
        "La poesia catalana contemporània", "El teatre català contemporani",
        "La literatura catalana actual", "Nous escriptors catalans",
        "Literatura catalana i gènere", "Escriptores catalanes",
        "Literatura infantil catalana", "Literatura juvenil catalana",
        "El conte català", "La narrativa curta catalana",
        "Literatura catalana i traducció", "La recepció de la literatura catalana",
        "Literatura catalana i identitat", "Llengua i literatura catalana",
        "Jaume Cabré: obra narrativa", "Quim Monzó: el conte i la ironia",
        "Imma Monsó: narrativa femenina", "Maria Barbal: novel·la i memòria",
    ],
    "Literatura catalana--S.XX": [
        "La literatura catalana al segle XX", "Panorama de la literatura catalana del XX",
        "La literatura catalana entre dues guerres", "La literatura catalana durant la República",
        "Literatura i Guerra Civil a Catalunya", "La repressió cultural franquista",
        "La literatura catalana clandestina", "Literatura catalana i resistència",
        "La literatura catalana dels anys 40", "La literatura catalana dels anys 50",
        "La generació dels 50 a Catalunya", "La literatura catalana dels anys 60",
        "El realisme social en la literatura catalana", "La novel·la catalana dels 60",
        "La literatura catalana de la Transició", "La literatura catalana dels 80",
        "La nova narrativa catalana", "La literatura catalana dels 90",
        "Escriptors catalans del XX", "Premi d'Honor de les Lletres Catalanes",
        "Els premis literaris catalans", "El Premi Sant Jordi de novel·la",
        "La crítica literària catalana al XX", "Les revistes literàries catalanes",
        "Les editorials catalanes al XX", "La recuperació editorial catalana",
        "Edicions 62 i la literatura catalana", "La poesia catalana del XX",
        "La novel·la catalana del XX", "El teatre català del XX",
        "L'assaig català del XX", "La literatura de memòria a Catalunya",
        "Diari i memòries en la literatura catalana", "Literatura i exili català",
        "Els escriptors catalans a Mèxic", "La literatura catalana a França",
        "Mercè Rodoreda al segle XX", "Salvador Espriu al segle XX",
        "Manuel de Pedrolo: obra i compromís", "Terenci Moix i la nova narrativa",
        "Quim Monzó i el conte català", "La generació dels 70",
        "La literatura catalana als anys 80 i 90", "Narrativa catalana contemporània",
        "El teatre català de la Transició", "La poesia dels anys 70 a Catalunya",
        "Joan Perucho: narrativa fantàstica", "Maria Aurèlia Capmany: escriptora i feminista",
        "Baltasar Porcel: narrativa i identitat", "Montserrat Roig: literatura i compromís",
    ],
    "Novel·la catalana": [
        "La novel·la catalana: una historia", "Evolució de la novel·la catalana",
        "La novel·la catalana medieval", "Tirant lo Blanc: lectura i anàlisi",
        "La novel·la realista catalana", "La novel·la modernista catalana",
        "La novel·la catalana d'entreguerres", "La novel·la catalana de postguerra",
        "La novel·la catalana contemporània", "La nova novel·la catalana",
        "Novel·la i identitat catalana", "Novel·la catalana i compromís polític",
        "La novel·la negra catalana", "El gènere negre en català",
        "La novel·la d'aventures catalana", "La novel·la històrica catalana",
        "La novel·la de ciència-ficció en català", "La novel·la fantàstica catalana",
        "La novel·la gràfica catalana", "Novel·la catalana i traducció",
        "Mercè Rodoreda: la novel·la", "La plaça del Diamant",
        "Mirall trencat de Rodoreda", "Llorenç Villalonga: Bearn",
        "Manuel de Pedrolo: novel·les", "Mecanoscrit del segon origen",
        "Joan Sales: Incerta glòria", "Pere Calders: novel·la i conte",
        "Terenci Moix: novel·les", "El dia que va morir Marilyn",
        "Quim Monzó: narrativa", "Jaume Cabré: novel·les",
        "Jo confesso de Cabré", "Les veus del Pamano",
        "Maria Barbal: Pedra de tartera", "Carme Riera: novel·la",
        "Isabel-Clara Simó: narrativa", "Víctor Català: Solitud",
        "La novel·la rural catalana", "La novel·la urbana catalana",
        "Barcelona en la novel·la catalana", "La novel·la del mar",
        "La novel·la de la memòria", "Novel·la i testimoni",
        "Novel·la epistolar catalana", "La novel·la policial catalana",
        "Andreu Martín: novel·la negra", "La novel·la d'iniciació catalana",
        "Novel·la catalana per a joves", "Els clàssics de la novel·la catalana",
    ],
    "Poesia catalana": [
        "Història de la poesia catalana", "Antologia de la poesia catalana",
        "La poesia catalana medieval", "Els trobadors catalans",
        "La lírica provençal a Catalunya", "Ausiàs March: poesia",
        "La poesia del segle d'or català", "La Renaixença poètica",
        "Jacint Verdaguer: poesia", "Canigó de Verdaguer",
        "Joan Maragall: els poemes", "El cant espiritual",
        "Joan Alcover i la poesia mallorquina", "Costa i Llobera: poesia",
        "El Modernisme poètic", "Joan Salvat-Papasseit: poemes",
        "J.V. Foix: poesia i avantguarda", "Sol, i de dol de Foix",
        "Carles Riba: les elegies", "Estances de Carles Riba",
        "La poesia noucentista", "Josep Carner: els poemes",
        "Guerau de Liost: la muntanya d'ametistes", "Clementina Arderiu: poesia",
        "Salvador Espriu: poesia", "La pell de brau d'Espriu",
        "Cementiri de Sinera", "Miquel Martí i Pol: poesia",
        "El llibre dels sis sentits", "Estimada Marta de Martí i Pol",
        "Joan Brossa: poesia i acció", "Poesia visual de Brossa",
        "Gabriel Ferrater: les dones i els dies", "Màrius Torres: poesia",
        "Pere Quart: humor i poesia", "Vicent Andrés Estellés: poesia",
        "Joan Vinyoli: poesia", "La poesia catalana de postguerra",
        "La poesia catalana dels 60", "La poesia catalana contemporània",
        "Poetes catalans contemporanis", "La poesia experimental catalana",
        "Poesia i música catalana", "Cançó i poesia a Catalunya",
        "La Nova Cançó i la poesia", "Poesia catalana i traducció",
        "Poetes catalanes", "Poesia catalana femenina",
        "La poesia dels Països Catalans", "Poesia catalana actual",
    ],
    "Història de Catalunya": [
        "Història de Catalunya", "Catalunya: una introducció històrica",
        "Breu història de Catalunya", "Síntesi de la història de Catalunya",
        "Els orígens de Catalunya", "La prehistòria a Catalunya",
        "Els ibers a Catalunya", "La colonització grega a Catalunya",
        "La Catalunya romana", "Tarraco, capital de la Hispania Citerior",
        "Les invasions bàrbares a Catalunya", "La Catalunya visigoda",
        "La conquesta àrab de Catalunya", "Els orígens del comtat de Barcelona",
        "Guifré el Pilós i la fundació de Catalunya", "Els comtes de Barcelona",
        "La Catalunya medieval", "L'expansió de la Corona d'Aragó",
        "Jaume I el Conqueridor", "La Catalunya dels segles XIV i XV",
        "La crisi del segle XV a Catalunya", "Catalunya i els Reis Catòlics",
        "La Catalunya moderna", "La Guerra dels Segadors",
        "El Corpus de Sang", "La Guerra de Successió",
        "L'11 de setembre de 1714", "La Catalunya del segle XVIII",
        "La Nova Planta a Catalunya", "Catalunya a l'època napoleònica",
        "El segle XIX a Catalunya", "La industrialització catalana",
        "La Renaixença catalana", "Catalunya i el moviment obrer",
        "L'anarquisme a Catalunya", "El catalanisme polític",
        "La Mancomunitat de Catalunya", "La Catalunya de la República",
        "La transició democràtica a Catalunya", "L'Estatut de 1979",
        "La Catalunya autònoma", "La Catalunya contemporània",
        "Economia i societat a Catalunya", "La cultura catalana",
        "Els símbols nacionals catalans", "La senyera i els quatre pals",
        "Les institucions catalanes", "El Parlament de Catalunya",
        "La Generalitat de Catalunya", "Catalunya i Espanya",
    ],
    "Història de Catalunya--S.XX": [
        "Catalunya al segle XX", "La Catalunya del nou-cents",
        "La Setmana Tràgica de 1909", "El pistolerisme a Barcelona",
        "La Mancomunitat de Catalunya 1914-1925", "La dictadura de Primo de Rivera a Catalunya",
        "La Catalunya de la República 1931-1939", "L'Estatut de Núria",
        "La Generalitat republicana", "La Catalunya en guerra 1936-1939",
        "La rereguarda catalana", "La revolució social de 1936",
        "Les col·lectivitzacions a Catalunya", "La fi de la Guerra Civil",
        "La retirada de 1939", "L'exili català",
        "La repressió franquista a Catalunya", "La postguerra a Catalunya",
        "La clandestinitat antifranquista", "La resistència cultural catalana",
        "El PSUC i el moviment obrer", "Les vagues dels anys 50 i 60",
        "El moviment estudiantil català", "El 1968 a Catalunya",
        "La cultura catalana en la clandestinitat", "Nova Cançó i resistència",
        "El tardofranquisme a Catalunya", "La Transició democràtica a Catalunya",
        "L'Assemblea de Catalunya", "Els pactes de la Moncloa",
        "L'Estatut de Sau", "El referèndum estatutari de 1979",
        "La Catalunya de Pujol", "La política catalana dels 80",
        "Els Jocs Olímpics de 1992", "La transformació de Barcelona",
        "La Catalunya dels 90", "El Fòrum de les Cultures 2004",
        "La Catalunya del segle XXI", "El procés sobiranista",
        "Economia catalana al segle XX", "Societat catalana al segle XX",
        "La immigració a Catalunya al XX", "Barcelona al segle XX",
        "L'urbanisme barceloní al XX", "La cultura popular catalana al XX",
        "Les festes populars catalanes", "El associacionisme català",
        "La premsa catalana al XX", "Ràdio i televisió a Catalunya",
    ],
    "Guerra Civil Espanyola, 1936-1939--Catalunya": [
        "La Guerra Civil a Catalunya", "Catalunya en guerra 1936-1939",
        "La revolució de juliol de 1936 a Catalunya", "Les milícies catalanes",
        "La columna Durruti", "Les Brigades Internacionals a Catalunya",
        "La batalla de l'Ebre", "La batalla del Segre",
        "La rereguarda republicana a Catalunya", "Barcelona en guerra",
        "Els bombardeigs de Barcelona", "La destrucció de Lleida",
        "Girona i la Guerra Civil", "La revolució social anarquista",
        "Les col·lectivitzacions agràries", "El POUM i els fets de maig de 1937",
        "Els Fets de Maig de 1937", "La repressió a la rereguarda",
        "L'Església i la Guerra Civil a Catalunya", "Refugiats i desplaçats",
        "Els nens de la guerra", "L'evacuació de la població civil",
        "La fi de la guerra a Catalunya", "La caiguda de Barcelona",
        "La retirada cap a França", "Els camps de refugiats a França",
        "L'exili republicà català", "Els catalans a Mèxic",
        "La repressió franquista a Catalunya", "Els afusellaments",
        "Les presons franquistes", "La depuració de funcionaris",
        "La repressió cultural", "La prohibició del català",
        "Memòria de la Guerra Civil a Catalunya", "Les fosses comunes",
        "La recuperació de la memòria histórica", "Fotografies de la Guerra Civil",
        "La premsa durant la Guerra Civil", "La propaganda republicana",
        "Art i Guerra Civil a Catalunya", "Cinema i Guerra Civil",
        "Literatura i Guerra Civil a Catalunya", "Testimonis de la Guerra Civil",
        "Dietaris i memòries de la Guerra Civil", "La sanitat durant la guerra",
        "Les dones i la Guerra Civil a Catalunya", "Infants i guerra",
        "Economia de guerra a Catalunya", "La indústria de guerra",
    ],
    "Llengua catalana": [
        "Història de la llengua catalana", "Origen i evolució del català",
        "El català: una llengua romànica", "La família de les llengües romàniques",
        "El llatí vulgar i el català", "El català antic",
        "El català medieval", "El català modern",
        "El català contemporani", "Dialectes del català",
        "El dialecte occidental", "El dialecte oriental",
        "El valenciá i el català", "El mallorquí i el català",
        "La unitat de la llengua catalana", "Sociolingüística catalana",
        "La situació sociolingüística del català", "El català a Catalunya",
        "El català al País Valencià", "El català a les Illes Balears",
        "El català a Andorra", "El català a la Catalunya del Nord",
        "La normalització lingüística", "La política lingüística a Catalunya",
        "La Llei de Política Lingüística", "L'ensenyament en català",
        "La immersió lingüística", "El català i el castellà a Catalunya",
        "Bilingüisme i diglòssia", "El futur del català",
        "El català a internet", "El català als mitjans de comunicació",
        "El català en la literatura", "El català en la ciència",
        "Terminologia catalana", "Neologismes en català",
        "Fonètica catalana", "Fonologia del català",
        "Morfologia catalana", "Sintaxi catalana",
        "Lexicografia catalana", "Diccionaris de la llengua catalana",
        "L'Institut d'Estudis Catalans", "La normativa de l'IEC",
        "El català col·loquial", "Variació lingüística en català",
        "Lingüística catalana", "Estudis romànics i català",
        "El català a l'Alguer", "Planificació lingüística",
    ],
    "Llengua catalana--Gramàtica": [
        "Gramàtica de la llengua catalana", "Gramàtica catalana",
        "Gramàtica normativa del català", "Gramàtica descriptiva del català",
        "Gramàtica del català contemporani", "Introducció a la gramàtica catalana",
        "Fonètica i fonologia catalanes", "Els sons del català",
        "La síl·laba en català", "L'accent en català",
        "La morfologia catalana", "Les parts de l'oració en català",
        "El nom en català", "El gènere i el nombre en català",
        "L'article en català", "Els determinants catalans",
        "L'adjectiu en català", "Els pronoms catalans",
        "Els pronoms febles", "El verb català",
        "La conjugació verbal catalana", "Els temps verbals en català",
        "L'aspecte verbal", "El mode verbal en català",
        "Les perífrasis verbals", "L'adverbi en català",
        "Les preposicions catalanes", "Les conjuncions catalanes",
        "La sintaxi catalana", "L'oració simple en català",
        "L'oració composta", "La subordinació en català",
        "La coordinació", "L'estil directe i indirecte",
        "La passiva en català", "La impersonalitat en català",
        "Ortografia catalana", "Les regles d'accentuació",
        "La puntuació en català", "L'apostrofació",
        "La contracció en català", "Exercicis de gramàtica catalana",
        "Gramàtica per a estrangers", "Català per a no catalanoparlants",
        "Gramàtica catalana avançada", "La normativa gramatical de l'IEC",
        "El català estàndard", "Estilística catalana",
        "Redacció en català", "L'escriptura acadèmica en català",
    ],
    "Cuina catalana": [
        "La cuina catalana", "Cuina catalana tradicional",
        "Història de la cuina catalana", "Els orígens de la cuina catalana",
        "La cuina catalana medieval", "Receptari medieval català",
        "El Llibre de Sent Soví", "La cuina catalana del segle XIX",
        "La cuina catalana moderna", "La cuina catalana contemporània",
        "La nova cuina catalana", "La cuina d'avantguarda a Catalunya",
        "Ferran Adrià i la cuina catalana", "El Bulli: cuina i creativitat",
        "La cuina catalana de mercat", "Els productes de la cuina catalana",
        "La trilogia catalana: pa, vi i oli", "L'oli d'oliva a Catalunya",
        "El vi català", "El pa català",
        "Els embotits catalans", "El formatge català",
        "La botifarra", "El pa amb tomàquet",
        "L'escudella i carn d'olla", "La calçotada",
        "Els calçots de Valls", "La romesco",
        "La cuina de la costa catalana", "El peix a la cuina catalana",
        "La cuina de l'interior", "Les carns a la cuina catalana",
        "La cuina de muntanya", "La cuina pirinenca",
        "Les postres catalanes", "La crema catalana",
        "Els pastissos catalans", "La coca catalana",
        "La cuina de Nadal a Catalunya", "La cuina de Setmana Santa",
        "Les festes i la cuina catalana", "La cuina popular catalana",
        "Receptes de cuina catalana", "Cuina catalana fàcil",
        "Guia de restaurants de Catalunya", "Gastronomia catalana",
        "El cava català", "La cuina de l'Empordà",
        "La cuina de les Terres de l'Ebre", "Cuina catalana i salut",
    ],
    "Música catalana": [
        "Història de la música catalana", "La música a Catalunya",
        "La música catalana medieval", "El cant gregorià a Catalunya",
        "La polifonia catalana medieval", "La música dels trobadors",
        "La música catalana del Renaixement", "La música catalana del Barroc",
        "La música catalana del segle XIX", "La Renaixença musical",
        "Felip Pedrell i la música catalana", "Isaac Albéniz i Catalunya",
        "Enric Granados: vida i obra", "Pau Casals: músic i humanista",
        "La música catalana del segle XX", "La Nova Cançó",
        "Raimon: la veu del País Valencià", "Joan Manuel Serrat: cançó i poesia",
        "Lluís Llach: compromís i música", "Maria del Mar Bonet: veu i tradició",
        "Els Setze Jutges", "La cançó catalana contemporània",
        "El rock català", "Sopa de Cabra i el rock català",
        "Els Pets: la música popular", "La música clàssica catalana contemporània",
        "Frederic Mompou: música i silenci", "Roberto Gerhard: avantguarda",
        "La sardana: música i dansa", "El cant coral català",
        "L'Orfeó Català", "El Palau de la Música Catalana i la música",
        "Les cobles i la sardana", "La música tradicional catalana",
        "Els instruments tradicionals catalans", "La gralla",
        "La música de cobla", "L'havanera a Catalunya",
        "Les cantades d'havaneres", "El jazz a Catalunya",
        "La música electrònica catalana", "La música per a cinema a Catalunya",
        "Educació musical a Catalunya", "Montserrat Caballé: soprano",
        "Josep Carreras: tenor", "Victoria de los Ángeles",
        "El Gran Teatre del Liceu", "L'òpera a Catalunya",
        "Els festivals de música catalana", "Música coral catalana",
    ],
    "Música--Catalunya--S.XX": [
        "La música a Catalunya al segle XX", "Panorama musical català del XX",
        "La música catalana de la Belle Époque", "La música a Barcelona 1900-1936",
        "L'avantguarda musical a Catalunya", "El Grup dels Vuit",
        "La música i la República catalana", "Música i Guerra Civil a Catalunya",
        "La repressió musical franquista", "La música catalana a l'exili",
        "La reconstrucció musical catalana", "La música catalana dels 50",
        "La música catalana dels 60", "La Nova Cançó i els anys 60",
        "La música catalana dels 70", "El rock progressiu català",
        "La música catalana dels 80", "El pop català dels 80",
        "La música catalana dels 90", "El rock català dels 90",
        "La música independent catalana", "El hip-hop en català",
        "La música electrònica a Catalunya", "Festivals de música a Catalunya",
        "El Sónar: música i tecnologia", "El Primavera Sound",
        "El Festival de Peralada", "La indústria discogràfica catalana",
        "Els segells discogràfics catalans", "La difusió de la música catalana",
        "Catalunya Música", "La crítica musical catalana al XX",
        "L'ensenyament musical a Catalunya al XX", "El Conservatori del Liceu",
        "L'ESMUC: Escola Superior de Música", "Els músics catalans al món",
        "Orquestres catalanes del XX", "L'OBC: Orquestra Simfònica de Barcelona",
        "El Gran Teatre del Liceu al XX", "L'Òpera a Catalunya al XX",
        "Xavier Montsalvatge: obra musical", "Frederic Mompou al segle XX",
        "La sardana al segle XX", "El cant coral català al XX",
        "L'Orfeó Català al XX", "La música tradicional catalana al XX",
        "El jazz català al segle XX", "La Nova Cançó: historia i llegat",
        "Iceberg i el jazz-rock català", "La cobla al segle XX",
    ],
    "Biologia": [
        "Introducció a la biologia", "Biologia general",
        "Fonaments de biologia", "Biologia cel·lular",
        "La cèl·lula: estructura i funció", "Biologia molecular",
        "El DNA i la genètica molecular", "Genètica",
        "Herència i genètica", "Evolució biològica",
        "La teoria de l'evolució", "Darwin i l'evolucionisme",
        "Ecologia", "Ecologia dels ecosistemes",
        "Biodiversitat", "La conservació de la biodiversitat",
        "Zoologia", "Botànica",
        "Microbiologia", "Els microorganismes",
        "Virologia", "Els virus i les malalties",
        "Fisiologia animal", "Fisiologia vegetal",
        "Anatomia comparada", "Embriologia",
        "Neurociència", "El sistema nerviós",
        "Immunologia", "El sistema immunitari",
        "Biotecnologia", "Enginyeria genètica",
        "Bioinformàtica", "Biologia sistèmica",
        "Biofísica", "Bioquímica",
        "Biology: A Global Approach", "Campbell Biology",
        "Molecular Biology of the Cell", "The Selfish Gene",
        "Biologia marina", "Biologia de la conservació",
        "Biologia de la reproducció", "Biologia del desenvolupament",
        "Cronobiologia", "Biologia de l'envelliment",
        "Astro-biologia", "Biologia i ètica",
        "Bioètica", "Biologia sintètica",
        "CRISPR i l'edició genètica", "Biologia i medicina",
    ],
    "Medicina--Catalunya": [
        "Història de la medicina a Catalunya", "La medicina catalana medieval",
        "La medicina catalana del Renaixement", "La medicina catalana del segle XIX",
        "La medicina catalana del segle XX", "El sistema sanitari català",
        "La sanitat pública a Catalunya", "CatSalut: el sistema de salut",
        "L'Hospital de la Santa Creu i Sant Pau", "L'Hospital Clínic de Barcelona",
        "La Vall d'Hebron: història i present", "Els hospitals catalans",
        "La medicina rural a Catalunya", "L'atenció primària a Catalunya",
        "Els CAPs a Catalunya", "La medicina privada a Catalunya",
        "La indústria farmacèutica catalana", "La recerca mèdica a Catalunya",
        "L'IDIBAPS: recerca biomèdica", "El VHIR: recerca sanitària",
        "La medicina universitària a Catalunya", "La Facultat de Medicina de Barcelona",
        "La formació de metges a Catalunya", "El Col·legi de Metges de Catalunya",
        "Les infermeres catalanes", "La infermeria a Catalunya",
        "La medicina tradicional catalana", "Les herbes medicinals catalanes",
        "La fitoteràpia catalana", "La salut mental a Catalunya",
        "La psiquiatria catalana", "La salut pública a Catalunya",
        "Les epidèmies a Catalunya", "La grip del 1918 a Catalunya",
        "La COVID-19 a Catalunya", "La salut laboral a Catalunya",
        "La medicina esportiva a Catalunya", "La geriatria a Catalunya",
        "La pediatria catalana", "La oncologia a Catalunya",
        "La cardiologia catalana", "Avenços mèdics a Catalunya",
        "La neurologia catalana", "La cirurgia a Catalunya",
        "Transplantaments a Catalunya", "La bioètica a Catalunya",
        "Recerca clínica a Catalunya", "La medicina de precisió",
        "La telemedicina a Catalunya", "Salut i qualitat de vida",
    ],
}

all_records = []

# Single-label records
for materia, titols in titols_per_materia.items():
    for titol in titols:
        all_records.append({"titol": titol, "materies": [materia]})

# Multi-label records
titols_multi = [
    ("Arquitectura i literatura a Catalunya", ["Arquitectura--Catalunya", "Literatura catalana"]),
    ("L'esport i la cultura catalana al segle XX", ["Esports--Catalunya", "Història de Catalunya--S.XX"]),
    ("Llengua i literatura catalanes", ["Llengua catalana", "Literatura catalana"]),
    ("Història i cultura de Catalunya", ["Història de Catalunya", "Literatura catalana"]),
    ("La cuina i la cultura catalana", ["Cuina catalana", "Història de Catalunya"]),
    ("Música i poesia catalana", ["Música catalana", "Poesia catalana"]),
    ("L'arquitectura i la història de Catalunya", ["Arquitectura--Catalunya", "Història de Catalunya"]),
    ("El futbol i la identitat catalana", ["Futbol--Catalunya", "Història de Catalunya--S.XX"]),
    ("La gramàtica i la literatura catalanes", ["Llengua catalana--Gramàtica", "Literatura catalana"]),
    ("La Guerra Civil i la cultura catalana", ["Guerra Civil Espanyola, 1936-1939--Catalunya", "Literatura catalana"]),
    ("La medicina i la societat catalana", ["Medicina--Catalunya", "Història de Catalunya--S.XX"]),
    ("La música i l'esport a Catalunya", ["Música--Catalunya--S.XX", "Esports--Catalunya"]),
    ("Arquitectura i urbanisme al segle XX", ["Arquitectura", "Arquitectura--S.XX"]),
    ("Novel·la i poesia catalana contemporània", ["Novel·la catalana", "Poesia catalana"]),
    ("L'esport i la llengua catalana", ["Esports--Catalunya", "Llengua catalana"]),
    ("La cuina i la medicina catalanes", ["Cuina catalana", "Medicina--Catalunya"]),
    ("Història i arquitectura de Catalunya", ["Arquitectura--Catalunya", "Història de Catalunya"]),
    ("La biologia i la medicina", ["Biologia", "Medicina--Catalunya"]),
    ("El futbol i la cultura catalana", ["Futbol--Catalunya", "Literatura catalana--S.XX"]),
    ("Llengua i gramàtica catalanes avançades", ["Llengua catalana", "Llengua catalana--Gramàtica"]),
    ("L'arquitectura modernista i la música catalana", ["Arquitectura--Catalunya", "Música catalana"]),
    ("Literatura i Guerra Civil a Catalunya", ["Literatura catalana--S.XX", "Guerra Civil Espanyola, 1936-1939--Catalunya"]),
    ("Esport i salut: medicina esportiva", ["Esports", "Medicina--Catalunya"]),
    ("La cuina i la literatura catalanes", ["Cuina catalana", "Literatura catalana"]),
    ("El futbol català al segle XX", ["Futbol--Catalunya", "Esports--Catalunya", "Història de Catalunya--S.XX"]),
    ("Literatura, llengua i identitat catalanes", ["Literatura catalana", "Llengua catalana", "Història de Catalunya"]),
    ("Arquitectura, art i cultura a Catalunya", ["Arquitectura--Catalunya", "Literatura catalana", "Història de Catalunya"]),
    ("La Nova Cançó i la resistència cultural", ["Música--Catalunya--S.XX", "Història de Catalunya--S.XX", "Literatura catalana--S.XX"]),
    ("Medicina, biologia i ciència a Catalunya", ["Medicina--Catalunya", "Biologia", "Història de Catalunya--S.XX"]),
    ("Cuina, festes i tradicions catalanes", ["Cuina catalana", "Història de Catalunya"]),
    ("Esport, política i nació catalana", ["Esports--Catalunya", "Història de Catalunya--S.XX", "Futbol--Catalunya"]),
    ("Llengua, literatura i escola catalana", ["Llengua catalana", "Literatura catalana", "Història de Catalunya"]),
    ("Arquitectura gòtica i romànica a Catalunya", ["Arquitectura--Catalunya", "Història de Catalunya"]),
    ("Poesia, cançó i música catalana", ["Poesia catalana", "Música catalana"]),
    ("Novel·la negra i thriller català", ["Novel·la catalana", "Literatura catalana--S.XX"]),
    ("Guerra Civil, exili i literatura", ["Guerra Civil Espanyola, 1936-1939--Catalunya", "Literatura catalana--S.XX"]),
    ("Futbol, esport i salut", ["Futbol--Catalunya", "Esports", "Medicina--Catalunya"]),
    ("Gramàtica, ortografia i redacció catalana", ["Llengua catalana--Gramàtica", "Llengua catalana"]),
    ("Biologia marina i ecologia costanera", ["Biologia", "Història de Catalunya"]),
    ("Hospitals, metges i salut pública", ["Medicina--Catalunya", "Història de Catalunya--S.XX"]),
]

for titol, materies in titols_multi:
    all_records.append({"titol": titol, "materies": materies})

random.shuffle(all_records)
all_records = all_records[:2000]

print(f"Total records: {len(all_records)}")

comptador = Counter(m for r in all_records for m in r["materies"])
print(f"Unique subjects: {len(comptador)}")
print("\nDistribution:")
for m, c in sorted(comptador.items(), key=lambda x: -x[1]):
    print(f"  {c:4d}  {m}")

with open("data/training_data_test.json", "w", encoding="utf-8") as f:
    json.dump(all_records, f, ensure_ascii=False, indent=2)

print(f"\nSaved {len(all_records)} records!")
